# Generated by Django 5.1.4 on 2025-01-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nombre")),
                (
                    "document_number",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        verbose_name="Documento de Identidad",
                    ),
                ),
                (
                    "credit_card_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Número de Tarjeta de Crédito",
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Límite de Crédito",
                    ),
                ),
                (
                    "total_credit_used",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Total Credit Used",
                    ),
                ),
                (
                    "person_type",
                    models.CharField(
                        choices=[("JURIDICAL", "Jurídica"), ("PHYSICAL", "Física")],
                        default="PHYSICAL",
                        max_length=10,
                        verbose_name="Tipo Persona",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Estado")),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nombre")),
                (
                    "document_number",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        verbose_name="Documento de Identidad",
                    ),
                ),
                (
                    "work_shift",
                    models.CharField(
                        choices=[
                            ("MORNING", "Matutina"),
                            ("AFTERNOON", "Vespertina"),
                            ("NIGHT", "Nocturna"),
                        ],
                        default="MORNING",
                        max_length=10,
                        verbose_name="Tanda Laboral",
                    ),
                ),
                (
                    "commission_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Porcentaje de Comisión",
                    ),
                ),
                ("entry_date", models.DateField(verbose_name="Fecha de Ingreso")),
                ("is_active", models.BooleanField(default=True, verbose_name="Estado")),
            ],
            options={
                "verbose_name": "Empleado",
                "verbose_name_plural": "Empleados",
            },
        ),
    ]
