# Generated by Django 5.1.4 on 2025-01-21 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rent_date", models.DateField(verbose_name="Fecha de Renta")),
                ("return_date", models.DateField(verbose_name="Fecha de Devolución")),
                (
                    "total_days",
                    models.PositiveSmallIntegerField(
                        default=0, editable=False, verbose_name="Total de Días"
                    ),
                ),
                (
                    "price_per_day",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio por Día"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        verbose_name="Total a Pagar",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Comentario"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rents",
                        to="core.customer",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rents",
                        to="core.employee",
                        verbose_name="Empleado",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rents",
                        to="vehicles.vehicle",
                        verbose_name="Vehículo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Renta",
                "verbose_name_plural": "Rentas",
            },
        ),
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[("PRE_RENT", "Pre Rent"), ("POST_RENT", "Post Rent")],
                        default="PRE_RENT",
                        max_length=15,
                        verbose_name="Inspection Type",
                    ),
                ),
                ("has_scratches", models.BooleanField(verbose_name="Tiene Ralladuras")),
                (
                    "fuel_quantity",
                    models.CharField(
                        choices=[
                            ("QUARTER", "1/4"),
                            ("HALF", "1/2"),
                            ("THREE_QUARTERS", "3/4"),
                            ("FULL", "lleno"),
                        ],
                        default="FULL",
                        max_length=15,
                        verbose_name="Cantidad Combustible",
                    ),
                ),
                (
                    "has_spare_tire",
                    models.BooleanField(verbose_name="Tiene Goma Respuesta"),
                ),
                (
                    "has_broken_glass",
                    models.BooleanField(verbose_name="Tiene Cristal Roto"),
                ),
                ("has_jack", models.BooleanField(verbose_name="Tiene Gato")),
                (
                    "front_left_tire_condition",
                    models.CharField(
                        choices=[
                            ("VERY_BAD", "Muy Mal Estado"),
                            ("BAD", "Bad"),
                            ("REGULAR", "Regular"),
                            ("GOOD", "Buen Estado"),
                            ("VERY_GOOD", "Muy Buen Estado"),
                        ],
                        default="GOOD",
                        max_length=15,
                        verbose_name="Condición Goma Delantera Izquierda",
                    ),
                ),
                (
                    "front_right_tire_condition",
                    models.CharField(
                        choices=[
                            ("VERY_BAD", "Muy Mal Estado"),
                            ("BAD", "Bad"),
                            ("REGULAR", "Regular"),
                            ("GOOD", "Buen Estado"),
                            ("VERY_GOOD", "Muy Buen Estado"),
                        ],
                        default="GOOD",
                        max_length=15,
                        verbose_name="Condición Goma Delantera Derecha",
                    ),
                ),
                (
                    "rear_left_tire_condition",
                    models.CharField(
                        choices=[
                            ("VERY_BAD", "Muy Mal Estado"),
                            ("BAD", "Bad"),
                            ("REGULAR", "Regular"),
                            ("GOOD", "Buen Estado"),
                            ("VERY_GOOD", "Muy Buen Estado"),
                        ],
                        default="GOOD",
                        max_length=15,
                        verbose_name="Condición Goma Trasera Izquierda",
                    ),
                ),
                (
                    "rear_right_tire_condition",
                    models.CharField(
                        choices=[
                            ("VERY_BAD", "Muy Mal Estado"),
                            ("BAD", "Bad"),
                            ("REGULAR", "Regular"),
                            ("GOOD", "Buen Estado"),
                            ("VERY_GOOD", "Muy Buen Estado"),
                        ],
                        default="GOOD",
                        max_length=15,
                        verbose_name="Condición Goma Trasera Derecha",
                    ),
                ),
                ("inspection_date", models.DateField(verbose_name="Fecha Inspección")),
                ("is_active", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Comentario"),
                ),
                (
                    "inspection_employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="core.employee",
                        verbose_name="Empleado Inspección",
                    ),
                ),
                (
                    "rent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="rents.rent",
                        verbose_name="Renta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspección",
                "verbose_name_plural": "Inspecciones",
            },
        ),
    ]
